#!/usr/bin/env python3

import os
import sys
import io
import cgi

# Definir colores para la salida
RED = "\033[91m"
RESET = "\033[0m"
GREEN = "\033[92m"
CYAN = "\033[96m"

form = cgi.FieldStorage()
filename = form["files"].filename
filedata = form["files"].file.read()
with open(f"../upload/{filename}", "wb") as f:
	f.write(filedata)
print("Content-Type: text/html\r")
print("\r")  # Línea en blanco para finalizar la cabecera
